### ISSUE TITLE
How to set custom column width in config xml?

### ISSUE THREAD

**Issue by jeffchai** [zerouwar/Octopus#10]
FYI.
Do you have a hook to do it?

**Comment by zerouwar** [comment]
谢谢提的需求，1.1.3会增加列宽度配置

钩子的话，可以重写`AbstractSheetWriter`的`drawColumn`方法，利用POI的API `Sheet#setColumnWidth`设置列宽度

PS:可以用中文提issues的

**Comment by zerouwar** [comment]
1.1.3版本已支持自定义列宽度配置
