### ISSUE TITLE
实际使用中发现的一些问题

### ISSUE THREAD

**Issue by huiyadanli** [zerouwar/Octopus#11]
1. 使用了 `options` 后该列必须不为空，个人认为该列是否为空应该由 `is-blankable` 判断。不然就无法处理该列选项可以为空的情况了。相关代码段：
https://github.com/zerouwar/Octopus/blob/91ae6d85d3307e471378737d2ecd5a98b3d8bff4/src/main/java/cn/chenhuanming/octopus/reader/CheckedSheetReader.java#L41-L56
2. 获得单元格数据之后使用 `String` 进行传参，大问题可能没有，我看过一些 excel 导入导出框架也是这么做的。不过在应对一些比较大的数，或者长小数时会出现科学计数法导致无法转换的问题（可以通过格式化解决）。
https://github.com/zerouwar/Octopus/blob/91ae6d85d3307e471378737d2ecd5a98b3d8bff4/src/main/java/cn/chenhuanming/octopus/util/CellUtils.java#L63-L80
3. 数字相关的 `Formatter` 没有做判空处理，也就是说空的数据转换为 `Integer` `Long` 之类的会报错。这个我也未作测试，存疑。

以上问题麻烦作者看下呐。这个框架的验证功能很好用，要是再加上表头验证的功能就好了。看了很多 excel 导入导出框架的源码，就 Octopus 的代码读着最舒适。

**Comment by zerouwar** [comment]
非常感谢提的PR。996，我尽量抽时间review😂

1. 使用了`options`之后，应该是不能为空，这个可以提前在读取配置的时候检查`options`，自动设置`is-blankable`为false
2. 大数字的问题还没怎么研究过呢，我要去看一下
3. 确实如果数据为空的时候大多会抛`NumberFormatException`，然后被`AbstractFormatter`转成`ParseException`抛出。对于对象类型应该返回null，基本类型返回默认值

**Comment by zerouwar** [comment]
另外，表头验证是什么意思

**Comment by huiyadanli** [comment]
> 另外，表头验证是什么意思

就是对这个复杂 header 的文字验证，确保用户是使用的正确的导入模板进行的导入。
这个功能我暂时也没什么实现思路。

![image](https://user-images.githubusercontent.com/15783049/60410758-587a8880-9bfc-11e9-9d48-16fc9a0e2d68.png)


然后，我提的PR就加了个常用类型的` Formatter` ，因为不清楚作者你的想法，并未提交以上内容的改动😂

**Comment by zerouwar** [comment]
1. 设置了`options`属性，就不能为空。在配置读取时会自动设置`is-blankable`为false
2. 新增`BigDecimalFormatter`，see #12
3. `AbstractFormatter`增加钩子方法检查空白字符串，代码如下
https://github.com/zerouwar/Octopus/blob/5a6b407d0fa83434801bc11d1bec6b22e8dcc9dc/src/main/java/cn/chenhuanming/octopus/formatter/AbstractFormatter.java#L28-L34

改动将应用到1.1.4版本

**Comment by zerouwar** [comment]
@huiyadanli 参照一下上面`AbstractFormatter `修改一下`BigDecimalFormatter `，有什么意见继续跟我反馈🙃

**Comment by huiyadanli** [comment]
已修改:stuck_out_tongue_closed_eyes:

**Comment by zerouwar** [comment]
我觉得表头验证不是那么强的需求，每个导入都有自己的格式限制，所以实现的话尽量跟主流程分离开来，可以开个接口做。欢迎继续提PR😂

**Comment by huiyadanli** [comment]
好的~
