### ISSUE TITLE
octopus.xsd无效

### ISSUE THREAD

**Issue by 605901202** [zerouwar/Octopus#13]
https://raw.githubusercontent.com/zerouwar/my-maven-repo/master/cn/chenhuanming/octopus/1.1.0/octopus.xsd 无法访问 是被墙了吗?

**Comment by zerouwar** [comment]
嗯我能打开，地址应该是被墙了。你可以直接删除`xsi:noNamespaceSchemaLocation`，我最新那版把xsd放到包里面了，不指定`xsi:noNamespaceSchemaLocation`会自动读取包里面的xsd

**Comment by zerouwar** [comment]
我后面把示例的`xsi:noNamespaceSchemaLocation`都删掉，默认读包里面的就好了
