### ISSUE TITLE
能否新增属性为集合对象

### ISSUE THREAD

**Issue by dockerDo** [zerouwar/Octopus#17]
public class Applicants {
    private int id;
    private String name;
    private List<Job> jobs;
    private Date entryDate;
    private boolean working = true;
}
大佬 能不能支持属性是集合的导出

**Comment by zerouwar** [comment]
你的意思是导出成这个样子吗
```
|         Job1        |         Job2        |
| job1Name | job1Desc | job2Name | job2Desc |
```

**Comment by dockerDo** [comment]
比如 一个订单 里面有多个商品信息

**Comment by youthlin** [comment]
可能是想要这样的？

| id | name | jobName | jobDesc | entryDate |
|---|------|------|-----|---|
| 1 | "case-1" | "job1" | "job1" | 2021-01-01 |
| 1 | "case-1" | "job2" | "job2" | 2021-01-01 |
| 2 | "case-2" | "job3" | "job3" | 2021-11-01 |

这种可以自己遍历 jobs 以每个 job 为一行，自己搞个中间结构复制公用的 id, name, entryDate 吧（或者留空，或者自行设置单元格合并）

| id | name | jobName | jobDesc | entryDate |
|---|------|------|-----|---|
| 1 | "case-1" | "job1" | "job1" | 2021-01-01 |
|  |   | "job2" | "job2" | |
| 2 | "case-2" | "job3" | "job3" | 2021-11-01 |

**Comment by dockerDo** [comment]
是下面这种 改动量点大呀 xml解析 注解解析 计算合并单元格 等等都要改

**Comment by zerouwar** [comment]
@dockerDo 多个job多行这种确实不太支持，框架设计时是按照一个数据一行设计。不过你还是可以复用配置解析和表头绘制等功能的，可以参考下`cn.chenhuanming.octopus.writer.AbstractSheetWriter#write`方法的for循环写excel行，你可以通过继承重写实现你想要的效果。

**Comment by zerouwar** [comment]
> 你的意思是导出成这个样子吗
> 
> ```
> |         Job1        |         Job2        |    entryDate
> | job1Name | job1Desc | job2Name | job2Desc |    2021-08-01
> ```

这种倒是可以支持一下，现在遇到Collection处理起来可能有点问题

**Comment by dockerDo** [comment]
1.解析的时候计算field 是否合并 返回值是否有集合
2.算出集合的长度 计算合并单元格 
3.计算下一行插入位置   
差不多就行了 ,


能顺便跟新输出多个单元格 和 同一个sheet 追加数据嘛?

**Comment by zerouwar** [comment]
@huiyadanli 1.1.5版本更新了，可以参考`AdvancedExample`的代码，里面有写多个sheet和往一个sheet追加的代码
