### ISSUE TITLE
两个小意见

### ISSUE THREAD

**Issue by Nowforpasserby** [zerouwar/Octopus#2]
首先,非常感谢作者这个工具, 实在是非常实用简洁,期待你的其他项目!!嘿嘿嘿!!!
1. RowAssemblerSheetReaderTest 跑完的exceptions 好像不是 bean 里面定义的 wrongMsg 吧
2. writer 的时候用 xml 好像也不是那么的优雅,你定义的ModelProperty标签里再加些属性去做这些事会不会更好

**Comment by zerouwar** [comment]
重构分支是dev-refactor，有兴趣可以先pull下来试试。可以跑ut看效果

**Comment by zerouwar** [comment]
1.0.0正式版发布了，完全重构了。暂时只支持XML配置了，因为XML和代码解耦，不过可以自己实现注解版配置，详细看文档。谢谢你提的issue，让我重新有动力完成了重构
