### ISSUE TITLE
能否跳过空行 或者 校验出空对象?

### ISSUE THREAD

**Issue by dockerDo** [zerouwar/Octopus#22]
![image](https://user-images.githubusercontent.com/37076860/134352302-6ee64284-ebf5-45d3-b962-3ae5142b6c5a.png)

**Comment by zerouwar** [comment]
`importData`是个`ArrayList`，直接`Stream#filter`一下就好了

**Comment by zerouwar** [comment]
空行还是需要上层业务感知的。有些业务情况是需要处理空行的，框架底层不好做忽略数据这种事情，容易出问题

如果你的业务是要做数据格式校验，可以用`Octopus.readFirstSheetWithValidation`方法，返回的数据集合是`CheckedData`类型，里面有格式校验的异常，但也是需要你自己去处理异常的。可以参考下[ReadMe-zh.md](https://github.com/zerouwar/Octopus/blob/master/README-zh.md#%E5%AF%BC%E5%85%A5%E6%A0%A1%E9%AA%8C%E6%95%B0%E6%8D%AE)
