### ISSUE TITLE
关于性能的咨询

### ISSUE THREAD

**Issue by c-rainstorm** [zerouwar/Octopus#7]
hello，请问项目有没有对性能做测试，能不能支持百万量级，30列的数据导出

**Comment by zerouwar** [comment]
性能方面不敢保证，建议压测一下，如果有压测结果可以共享一下喔，也可以直接提pr。Octopus只是封装了POI，底层完全调用POI的代码，可能内存消耗是个问题。另外我觉得百万数据的Excel也不太现实吧~

**Comment by zerouwar** [comment]
实现方面的话，`ConfigReader`是基于双重检查的单例模式，读取配置后会存储get,setter的Method对象以及`Formatter`实例，导出导入时直接调method.invoke

**Comment by c-rainstorm** [comment]
嗯嗯，好的。最近公司对导出报表有性能优化的需求，希望能尽可能高效的导出大数据量的报表，我先搞一波，有必要的话，可能周末会提 pr。

**Comment by zerouwar** [comment]
刚试了下导出10w条Applicant（就是文档里面复杂的例子），发现一个Bug，POI限制CellStyle的数量最大64000，没注意这个创建对象和限制。修好后，导出10w条要91秒，我先试一下定位瓶颈，有关性能问题在这里同步一下

**Comment by zerouwar** [comment]
现在导出的性能问题主要有有个地方：

1. `DefaultSheetWriter`在导出后会调POI的`Sheet.autoSizeColumn`方法，这个方法非常耗时。这里短期内很难优化，感觉要做出妥协，到达一定数据量暂时不自动调整列宽了
2. 原本是用POI的usermodel实现，大数据量时很耗内存和CPU，下一版改成用SXSSF实现，试了一下，改成SXSSF从91秒减少到了17秒

[POI官方关于SXSSF的文档](https://poi.apache.org/components/spreadsheet/)

**Comment by zerouwar** [comment]
1.1.0修复这个bug，默认用SXSSF导出，关闭issue
